seed: 0
device: cuda
load_model: false
logdir: /part/01/Tmp/max_entropy/logs
log_every: 1000
print_every: 10
dataset: MNIST
n_epoch: 10
batch_size: 64
can_sleep: true
sleep_itr: 1000
wake_lr: 0.01
sleep_lr: 0.01
